apiVersion: apps/v1
kind: Deployment
metadata:
  name: maverick-ui-dev
  namespace: maverick-ui
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: maverick-ui-dev
  template:
    metadata:
      labels:
        app: maverick-ui-dev
