apiVersion: apps/v1
kind: Deployment
metadata:
  name: maverick-ui-dev
  namespace: dev
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: frontend-fargate-dev
  template:
    metadata:
      labels:
        app: frontend-fargate-dev
