apiVersion: v1
kind: Service
metadata:
  name: maverick-ui
  namespace: dev
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: dev
spec:
  selector:
    app: frontend-fargate-dev
