apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 292526779943.dkr.ecr.eu-central-1.amazonaws.com/demo-frontend
  newName: 292526779943.dkr.ecr.eu-central-1.amazonaws.com/demo-frontend
  newTag: f2df6c1a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
