apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 292526779943.dkr.ecr.eu-central-1.amazonaws.com/app/maverick-ui/dev
  newName: 292526779943.dkr.ecr.eu-central-1.amazonaws.com/app/maverick-ui/dev
  newTag: c85e5de2
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
