---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: eu-central-1
  namespace: dev

fargateProfiles:
  - name: frontend-fargate-profile
    selectors:
      - namespace: dev
        labels:
          app: frontend-fargate
