---
apiVersion: v1
kind: Service
metadata:
  name: maverick-ui
  namespace: dev
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: frontend-fargate
  type: LoadBalancer #NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
