---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maverick-ui
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-fargate
  template:
    metadata:
      labels:
        app: frontend-fargate
    spec:
      containers:
        - name: maverick-ui
          image: 292526779943.dkr.ecr.eu-central-1.amazonaws.com/app/maverick-ui/dev:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
