apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: maverick-ui-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-kustomization-microservices-ui
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70